### ISSUE TITLE
Chapter 5, exercise 5.8 p.77

### ISSUE THREAD

**Issue by williamlai2** [avehtari/ROS-Examples#120]
Hi. this might be an error, though also might not. It is in the exercises for Chapter 5 (p.77)

In the first bit, we are working with standard error, but in (a) it is standard deviation.

> 5.8 Coverage of confidence intervals: On page 15 there is a discussion of an experimental study of
an education-related intervention in Jamaica, in which the point estimate of the treatment effect,
on the log scale, was 0.35 with a standard error of 0.17. Suppose the true effect is 0.10—this
seems more realistic than the point estimate of 0.35—so that the treatment on average would
increase earnings by 0.10 on the log scale. Use simulation to study the statistical properties of
this experiment, assuming the **standard error is 0.17**.
(a) Simulate 1000 independent replications of the experiment assuming that the point estimate is
normally distributed with mean 0.10 and **standard deviation 0.17**.

**Comment by andrewgelman** [comment]
"Standard error" is statistics jargon for "estimated standard deviation of an estimate" or "uncertainty of an estimate."  Thus, we use the term "standard error" in the first paragraph above because we are referring to an estimate, and we use the term "standard deviation" in the second paragraph because we are referring to a probability distribution.

We could have simply used the term "standard deviation" throughout, but then this could perhaps have led to confusion if people thought that 0.17 was the standard deviation of the measurements.  The term "standard error" is used to make it clear that we're talking about the standard deviation of an estimate.

**Comment by williamlai2** [comment]
Thanks for the info
