### ISSUE TITLE
Codebook

### ISSUE THREAD

**Issue by viviana-paulina** [avehtari/ROS-Examples#74]
Dear Dr. Vehtari,

Are you thinking of having codebooks for each dataset? So far, there are only 4 of them (e.g., sesame, NSW). I am particularly interested in the codebook of the childcare dataset of chapter 20.

Thank you in advance,

Viviana

**Comment by andrewgelman** [comment]
Hi, yes, I guess that would be a good idea!

**Comment by viviana-paulina** [comment]
Dear Professor Gelman, 

Very kind of you to reply to my message. Is the Chile school data from Kenneth Chay et al. paper published in AER (2005)?

**Comment by andrewgelman** [comment]
Hi, I'm not sure.  Jennifer would know.

**Comment by andrewgelman** [comment]
Yes.  We note that in the references at the end of the chapter.


Jennifer Hill
Professor of Applied Statistics
Director, PRIISM Center <https://steinhardt.nyu.edu/priism>
Co-Director, A3SR MS Program
<https://steinhardt.nyu.edu/programs/applied-statistics-social-science-research>
New York University

**Comment by avehtari** [comment]
I have added the data dictionary for Childcare https://github.com/avehtari/ROS-Examples/blob/master/Childcare/data/datadict.txt
and I copied the references from the book to the Childcare and ChileSchools so that references are easier to find.
Please let us know if there are other missing information.
